version: "3"

services:
  node:
    build: .
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    container_name: investiment_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      ROUTE_AXIOS: http://localhost:3001/
      JWT_SECRET: 96e2c84bf0244e7f8e4075b11ec81929
      DB_HOST: db.nrurasmyknotwfvzpoqh.supabase.co
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: n2ovZafx9tPrOhpH
      DB_NAME: postgres

networks:
  default:
    name: investiment_api_net